# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from to_back.ecotaxa_cli_py.configuration import Configuration


class BodyRemoveFileUserFilesRmPost(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'source_path': 'str'
    }

    attribute_map = {
        'source_path': 'source_path'
    }

    def __init__(self, source_path=None, local_vars_configuration=None):  # noqa: E501
        """BodyRemoveFileUserFilesRmPost - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._source_path = None
        self.discriminator = None

        if source_path is not None:
            self.source_path = source_path

    @property
    def source_path(self):
        """Gets the source_path of this BodyRemoveFileUserFilesRmPost.  # noqa: E501

        The client-side full path of the file , files list or file filter, or directory to be removed.  # noqa: E501

        :return: The source_path of this BodyRemoveFileUserFilesRmPost.  # noqa: E501
        :rtype: str
        """
        return self._source_path

    @source_path.setter
    def source_path(self, source_path):
        """Sets the source_path of this BodyRemoveFileUserFilesRmPost.

        The client-side full path of the file , files list or file filter, or directory to be removed.  # noqa: E501

        :param source_path: The source_path of this BodyRemoveFileUserFilesRmPost.  # noqa: E501
        :type: str
        """

        self._source_path = source_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyRemoveFileUserFilesRmPost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyRemoveFileUserFilesRmPost):
            return True

        return self.to_dict() != other.to_dict()
