# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.41
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from to_back.ecotaxa_cli_py.configuration import Configuration


class ProjectColumnsModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'projid': 'int',
        'columns': 'list[str]',
        'values': 'list[str]'
    }

    attribute_map = {
        'projid': 'projid',
        'columns': 'columns',
        'values': 'values'
    }

    def __init__(self, projid=None, columns=None, values=None, local_vars_configuration=None):  # noqa: E501
        """ProjectColumnsModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._projid = None
        self._columns = None
        self._values = None
        self.discriminator = None

        if projid is not None:
            self.projid = projid
        if columns is not None:
            self.columns = columns
        if values is not None:
            self.values = values

    @property
    def projid(self):
        """Gets the projid of this ProjectColumnsModel.  # noqa: E501

        Project ID from the call.  # noqa: E501

        :return: The projid of this ProjectColumnsModel.  # noqa: E501
        :rtype: int
        """
        return self._projid

    @projid.setter
    def projid(self, projid):
        """Sets the projid of this ProjectColumnsModel.

        Project ID from the call.  # noqa: E501

        :param projid: The projid of this ProjectColumnsModel.  # noqa: E501
        :type: int
        """

        self._projid = projid

    @property
    def columns(self):
        """Gets the columns of this ProjectColumnsModel.  # noqa: E501

        Column names from the call.  # noqa: E501

        :return: The columns of this ProjectColumnsModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this ProjectColumnsModel.

        Column names from the call.  # noqa: E501

        :param columns: The columns of this ProjectColumnsModel.  # noqa: E501
        :type: list[str]
        """

        self._columns = columns

    @property
    def values(self):
        """Gets the values of this ProjectColumnsModel.  # noqa: E501

        All rows regardless of emptiness.  # noqa: E501

        :return: The values of this ProjectColumnsModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this ProjectColumnsModel.

        All rows regardless of emptiness.  # noqa: E501

        :param values: The values of this ProjectColumnsModel.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectColumnsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectColumnsModel):
            return True

        return self.to_dict() != other.to_dict()
