# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.42
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from to_back.ecotaxa_cli_py.configuration import Configuration


class TaxonomyRecastReq(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'target_id': 'int',
        'operation': 'RecastOperation',
        'is_collection': 'bool',
        'recast': 'dict(str, str)'
    }

    attribute_map = {
        'target_id': 'target_id',
        'operation': 'operation',
        'is_collection': 'is_collection',
        'recast': 'recast'
    }

    def __init__(self, target_id=None, operation=None, is_collection=False, recast=None, local_vars_configuration=None):  # noqa: E501
        """TaxonomyRecastReq - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._target_id = None
        self._operation = None
        self._is_collection = None
        self._recast = None
        self.discriminator = None

        self.target_id = target_id
        if operation is not None:
            self.operation = operation
        if is_collection is not None:
            self.is_collection = is_collection
        self.recast = recast

    @property
    def target_id(self):
        """Gets the target_id of this TaxonomyRecastReq.  # noqa: E501

        The Collection or Project Id.  # noqa: E501

        :return: The target_id of this TaxonomyRecastReq.  # noqa: E501
        :rtype: int
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this TaxonomyRecastReq.

        The Collection or Project Id.  # noqa: E501

        :param target_id: The target_id of this TaxonomyRecastReq.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and target_id is None:  # noqa: E501
            raise ValueError("Invalid value for `target_id`, must not be `None`")  # noqa: E501

        self._target_id = target_id

    @property
    def operation(self):
        """Gets the operation of this TaxonomyRecastReq.  # noqa: E501

        Recast operation name.  # noqa: E501

        :return: The operation of this TaxonomyRecastReq.  # noqa: E501
        :rtype: RecastOperation
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this TaxonomyRecastReq.

        Recast operation name.  # noqa: E501

        :param operation: The operation of this TaxonomyRecastReq.  # noqa: E501
        :type: RecastOperation
        """

        self._operation = operation

    @property
    def is_collection(self):
        """Gets the is_collection of this TaxonomyRecastReq.  # noqa: E501

        If True the target_id is a Collection Id otherwise a Project Id.  # noqa: E501

        :return: The is_collection of this TaxonomyRecastReq.  # noqa: E501
        :rtype: bool
        """
        return self._is_collection

    @is_collection.setter
    def is_collection(self, is_collection):
        """Sets the is_collection of this TaxonomyRecastReq.

        If True the target_id is a Collection Id otherwise a Project Id.  # noqa: E501

        :param is_collection: The is_collection of this TaxonomyRecastReq.  # noqa: E501
        :type: bool
        """

        self._is_collection = is_collection

    @property
    def recast(self):
        """Gets the recast of this TaxonomyRecastReq.  # noqa: E501

        Recast taxonomy from key to value.  # noqa: E501

        :return: The recast of this TaxonomyRecastReq.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._recast

    @recast.setter
    def recast(self, recast):
        """Sets the recast of this TaxonomyRecastReq.

        Recast taxonomy from key to value.  # noqa: E501

        :param recast: The recast of this TaxonomyRecastReq.  # noqa: E501
        :type: dict(str, str)
        """
        if self.local_vars_configuration.client_side_validation and recast is None:  # noqa: E501
            raise ValueError("Invalid value for `recast`, must not be `None`")  # noqa: E501

        self._recast = recast

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaxonomyRecastReq):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TaxonomyRecastReq):
            return True

        return self.to_dict() != other.to_dict()
