# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.42
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from to_back.ecotaxa_cli_py.configuration import Configuration


class TaxonModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'type': 'str',
        'status': 'str',
        'display_name': 'str',
        'lineage': 'list[str]',
        'id_lineage': 'list[int]',
        'lineage_status': 'str',
        'renm_id': 'int',
        'nb_objects': 'int',
        'nb_children_objects': 'int',
        'aphia_id': 'int',
        'rank': 'str',
        'children': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'status': 'status',
        'display_name': 'display_name',
        'lineage': 'lineage',
        'id_lineage': 'id_lineage',
        'lineage_status': 'lineage_status',
        'renm_id': 'renm_id',
        'nb_objects': 'nb_objects',
        'nb_children_objects': 'nb_children_objects',
        'aphia_id': 'aphia_id',
        'rank': 'rank',
        'children': 'children'
    }

    def __init__(self, id=None, name=None, type=None, status=None, display_name=None, lineage=None, id_lineage=None, lineage_status=None, renm_id=None, nb_objects=None, nb_children_objects=None, aphia_id=None, rank=None, children=None, local_vars_configuration=None):  # noqa: E501
        """TaxonModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._type = None
        self._status = None
        self._display_name = None
        self._lineage = None
        self._id_lineage = None
        self._lineage_status = None
        self._renm_id = None
        self._nb_objects = None
        self._nb_children_objects = None
        self._aphia_id = None
        self._rank = None
        self._children = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.type = type
        self.status = status
        self.display_name = display_name
        self.lineage = lineage
        self.id_lineage = id_lineage
        self.lineage_status = lineage_status
        if renm_id is not None:
            self.renm_id = renm_id
        self.nb_objects = nb_objects
        self.nb_children_objects = nb_children_objects
        if aphia_id is not None:
            self.aphia_id = aphia_id
        if rank is not None:
            self.rank = rank
        self.children = children

    @property
    def id(self):
        """Gets the id of this TaxonModel.  # noqa: E501

        The taxon/category IDs.  # noqa: E501

        :return: The id of this TaxonModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TaxonModel.

        The taxon/category IDs.  # noqa: E501

        :param id: The id of this TaxonModel.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TaxonModel.  # noqa: E501

        The taxon/category verbatim name.  # noqa: E501

        :return: The name of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TaxonModel.

        The taxon/category verbatim name.  # noqa: E501

        :param name: The name of this TaxonModel.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this TaxonModel.  # noqa: E501

        The taxon/category type, 'M' for Morpho or 'P' for Phylo.  # noqa: E501

        :return: The type of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TaxonModel.

        The taxon/category type, 'M' for Morpho or 'P' for Phylo.  # noqa: E501

        :param type: The type of this TaxonModel.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def status(self):
        """Gets the status of this TaxonModel.  # noqa: E501

        The taxon/category status, 'D' for Deprecated, 'A' for Approved or 'N' for Notapproved.  # noqa: E501

        :return: The status of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TaxonModel.

        The taxon/category status, 'D' for Deprecated, 'A' for Approved or 'N' for Notapproved.  # noqa: E501

        :param status: The status of this TaxonModel.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def display_name(self):
        """Gets the display_name of this TaxonModel.  # noqa: E501

        The taxon/category display name.  # noqa: E501

        :return: The display_name of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this TaxonModel.

        The taxon/category display name.  # noqa: E501

        :param display_name: The display_name of this TaxonModel.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and display_name is None:  # noqa: E501
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def lineage(self):
        """Gets the lineage of this TaxonModel.  # noqa: E501

        The taxon/category name of ancestors, including self, in first.  # noqa: E501

        :return: The lineage of this TaxonModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._lineage

    @lineage.setter
    def lineage(self, lineage):
        """Sets the lineage of this TaxonModel.

        The taxon/category name of ancestors, including self, in first.  # noqa: E501

        :param lineage: The lineage of this TaxonModel.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and lineage is None:  # noqa: E501
            raise ValueError("Invalid value for `lineage`, must not be `None`")  # noqa: E501

        self._lineage = lineage

    @property
    def id_lineage(self):
        """Gets the id_lineage of this TaxonModel.  # noqa: E501

        The taxon/category IDs of ancestors, including self, in first.  # noqa: E501

        :return: The id_lineage of this TaxonModel.  # noqa: E501
        :rtype: list[int]
        """
        return self._id_lineage

    @id_lineage.setter
    def id_lineage(self, id_lineage):
        """Sets the id_lineage of this TaxonModel.

        The taxon/category IDs of ancestors, including self, in first.  # noqa: E501

        :param id_lineage: The id_lineage of this TaxonModel.  # noqa: E501
        :type: list[int]
        """
        if self.local_vars_configuration.client_side_validation and id_lineage is None:  # noqa: E501
            raise ValueError("Invalid value for `id_lineage`, must not be `None`")  # noqa: E501

        self._id_lineage = id_lineage

    @property
    def lineage_status(self):
        """Gets the lineage_status of this TaxonModel.  # noqa: E501

        The taxon ancestors' status, including self, in first.  # noqa: E501

        :return: The lineage_status of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._lineage_status

    @lineage_status.setter
    def lineage_status(self, lineage_status):
        """Sets the lineage_status of this TaxonModel.

        The taxon ancestors' status, including self, in first.  # noqa: E501

        :param lineage_status: The lineage_status of this TaxonModel.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and lineage_status is None:  # noqa: E501
            raise ValueError("Invalid value for `lineage_status`, must not be `None`")  # noqa: E501

        self._lineage_status = lineage_status

    @property
    def renm_id(self):
        """Gets the renm_id of this TaxonModel.  # noqa: E501

        The advised replacement ID if the taxon/category is deprecated.  # noqa: E501

        :return: The renm_id of this TaxonModel.  # noqa: E501
        :rtype: int
        """
        return self._renm_id

    @renm_id.setter
    def renm_id(self, renm_id):
        """Sets the renm_id of this TaxonModel.

        The advised replacement ID if the taxon/category is deprecated.  # noqa: E501

        :param renm_id: The renm_id of this TaxonModel.  # noqa: E501
        :type: int
        """

        self._renm_id = renm_id

    @property
    def nb_objects(self):
        """Gets the nb_objects of this TaxonModel.  # noqa: E501

        How many objects are classified in this category.  # noqa: E501

        :return: The nb_objects of this TaxonModel.  # noqa: E501
        :rtype: int
        """
        return self._nb_objects

    @nb_objects.setter
    def nb_objects(self, nb_objects):
        """Sets the nb_objects of this TaxonModel.

        How many objects are classified in this category.  # noqa: E501

        :param nb_objects: The nb_objects of this TaxonModel.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and nb_objects is None:  # noqa: E501
            raise ValueError("Invalid value for `nb_objects`, must not be `None`")  # noqa: E501

        self._nb_objects = nb_objects

    @property
    def nb_children_objects(self):
        """Gets the nb_children_objects of this TaxonModel.  # noqa: E501

        How many objects are classified in this category children (not itself).  # noqa: E501

        :return: The nb_children_objects of this TaxonModel.  # noqa: E501
        :rtype: int
        """
        return self._nb_children_objects

    @nb_children_objects.setter
    def nb_children_objects(self, nb_children_objects):
        """Sets the nb_children_objects of this TaxonModel.

        How many objects are classified in this category children (not itself).  # noqa: E501

        :param nb_children_objects: The nb_children_objects of this TaxonModel.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and nb_children_objects is None:  # noqa: E501
            raise ValueError("Invalid value for `nb_children_objects`, must not be `None`")  # noqa: E501

        self._nb_children_objects = nb_children_objects

    @property
    def aphia_id(self):
        """Gets the aphia_id of this TaxonModel.  # noqa: E501

        The WoRMS aphia_id of the taxon.  # noqa: E501

        :return: The aphia_id of this TaxonModel.  # noqa: E501
        :rtype: int
        """
        return self._aphia_id

    @aphia_id.setter
    def aphia_id(self, aphia_id):
        """Sets the aphia_id of this TaxonModel.

        The WoRMS aphia_id of the taxon.  # noqa: E501

        :param aphia_id: The aphia_id of this TaxonModel.  # noqa: E501
        :type: int
        """

        self._aphia_id = aphia_id

    @property
    def rank(self):
        """Gets the rank of this TaxonModel.  # noqa: E501

        The WoRMS rank of the taxon.  # noqa: E501

        :return: The rank of this TaxonModel.  # noqa: E501
        :rtype: str
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this TaxonModel.

        The WoRMS rank of the taxon.  # noqa: E501

        :param rank: The rank of this TaxonModel.  # noqa: E501
        :type: str
        """

        self._rank = rank

    @property
    def children(self):
        """Gets the children of this TaxonModel.  # noqa: E501

        The taxon/category IDs of children.  # noqa: E501

        :return: The children of this TaxonModel.  # noqa: E501
        :rtype: list[int]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this TaxonModel.

        The taxon/category IDs of children.  # noqa: E501

        :param children: The children of this TaxonModel.  # noqa: E501
        :type: list[int]
        """
        if self.local_vars_configuration.client_side_validation and children is None:  # noqa: E501
            raise ValueError("Invalid value for `children`, must not be `None`")  # noqa: E501

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaxonModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TaxonModel):
            return True

        return self.to_dict() != other.to_dict()
