# coding: utf-8

"""
    EcoTaxa

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.48
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from to_back.ecotaxa_cli_py.configuration import Configuration


class TaxoRecastSearchRsp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'recast_id': 'int',
        'collection_id': 'int',
        'project_id': 'int',
        'project_title': 'str',
        'operation': 'str',
        'transforms': 'dict(str, int)',
        'documentation': 'dict(str, str)'
    }

    attribute_map = {
        'recast_id': 'recast_id',
        'collection_id': 'collection_id',
        'project_id': 'project_id',
        'project_title': 'project_title',
        'operation': 'operation',
        'transforms': 'transforms',
        'documentation': 'documentation'
    }

    def __init__(self, recast_id=None, collection_id=None, project_id=None, project_title=None, operation=None, transforms=None, documentation=None, local_vars_configuration=None):  # noqa: E501
        """TaxoRecastSearchRsp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._recast_id = None
        self._collection_id = None
        self._project_id = None
        self._project_title = None
        self._operation = None
        self._transforms = None
        self._documentation = None
        self.discriminator = None

        self.recast_id = recast_id
        if collection_id is not None:
            self.collection_id = collection_id
        if project_id is not None:
            self.project_id = project_id
        if project_title is not None:
            self.project_title = project_title
        self.operation = operation
        self.transforms = transforms
        if documentation is not None:
            self.documentation = documentation

    @property
    def recast_id(self):
        """Gets the recast_id of this TaxoRecastSearchRsp.  # noqa: E501

        The taxo_recast record id.  # noqa: E501

        :return: The recast_id of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: int
        """
        return self._recast_id

    @recast_id.setter
    def recast_id(self, recast_id):
        """Sets the recast_id of this TaxoRecastSearchRsp.

        The taxo_recast record id.  # noqa: E501

        :param recast_id: The recast_id of this TaxoRecastSearchRsp.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and recast_id is None:  # noqa: E501
            raise ValueError("Invalid value for `recast_id`, must not be `None`")  # noqa: E501

        self._recast_id = recast_id

    @property
    def collection_id(self):
        """Gets the collection_id of this TaxoRecastSearchRsp.  # noqa: E501

        Set if the recast applies to a whole collection.  # noqa: E501

        :return: The collection_id of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: int
        """
        return self._collection_id

    @collection_id.setter
    def collection_id(self, collection_id):
        """Sets the collection_id of this TaxoRecastSearchRsp.

        Set if the recast applies to a whole collection.  # noqa: E501

        :param collection_id: The collection_id of this TaxoRecastSearchRsp.  # noqa: E501
        :type: int
        """

        self._collection_id = collection_id

    @property
    def project_id(self):
        """Gets the project_id of this TaxoRecastSearchRsp.  # noqa: E501

        Set if the recast applies to a single project.  # noqa: E501

        :return: The project_id of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this TaxoRecastSearchRsp.

        Set if the recast applies to a single project.  # noqa: E501

        :param project_id: The project_id of this TaxoRecastSearchRsp.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def project_title(self):
        """Gets the project_title of this TaxoRecastSearchRsp.  # noqa: E501

        The title of the project designated by project_id.  # noqa: E501

        :return: The project_title of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: str
        """
        return self._project_title

    @project_title.setter
    def project_title(self, project_title):
        """Sets the project_title of this TaxoRecastSearchRsp.

        The title of the project designated by project_id.  # noqa: E501

        :param project_title: The project_title of this TaxoRecastSearchRsp.  # noqa: E501
        :type: str
        """

        self._project_title = project_title

    @property
    def operation(self):
        """Gets the operation of this TaxoRecastSearchRsp.  # noqa: E501

        Recast operation name.  # noqa: E501

        :return: The operation of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this TaxoRecastSearchRsp.

        Recast operation name.  # noqa: E501

        :param operation: The operation of this TaxoRecastSearchRsp.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and operation is None:  # noqa: E501
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def transforms(self):
        """Gets the transforms of this TaxoRecastSearchRsp.  # noqa: E501

        Mapping from seen taxon (key) to output replacement one (value).  # noqa: E501

        :return: The transforms of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._transforms

    @transforms.setter
    def transforms(self, transforms):
        """Sets the transforms of this TaxoRecastSearchRsp.

        Mapping from seen taxon (key) to output replacement one (value).  # noqa: E501

        :param transforms: The transforms of this TaxoRecastSearchRsp.  # noqa: E501
        :type: dict(str, int)
        """
        if self.local_vars_configuration.client_side_validation and transforms is None:  # noqa: E501
            raise ValueError("Invalid value for `transforms`, must not be `None`")  # noqa: E501

        self._transforms = transforms

    @property
    def documentation(self):
        """Gets the documentation of this TaxoRecastSearchRsp.  # noqa: E501

        To keep memory of the reasons for the above mapping.  # noqa: E501

        :return: The documentation of this TaxoRecastSearchRsp.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._documentation

    @documentation.setter
    def documentation(self, documentation):
        """Sets the documentation of this TaxoRecastSearchRsp.

        To keep memory of the reasons for the above mapping.  # noqa: E501

        :param documentation: The documentation of this TaxoRecastSearchRsp.  # noqa: E501
        :type: dict(str, str)
        """

        self._documentation = documentation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaxoRecastSearchRsp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TaxoRecastSearchRsp):
            return True

        return self.to_dict() != other.to_dict()
