version: "3"
services:
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      econet:
    ports:
      - 8088:80
    depends_on:
      - ecotaxafront
      - ecotaxaback
  ecotaxafront:
    image: ecotaxa/ecotaxa_front:2.6.2
    volumes:
      - ../config:/app/config
    networks:
      econet:
    depends_on:
      - ecotaxaback
  ecotaxaback:
    image: ecotaxa/ecotaxa_back:2.6.2
    volumes:
      - ../../ecotaxa_back/py/config.ini:/config.ini
    networks:
      econet:
    depends_on:
      - db
  db:
    image: postgres:13.6
    networks:
      econet:
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
networks:
  econet:
    driver: bridge