# Necessary when you run with Vuejs
# Add this shell piece into your .bashrc
# Also add the cors-cache-proxy folder
# Follow directives of https://medium.com/swlh/setup-a-node-js-cors-proxy-with-caching-support-632e83ea82e6



# Run my CORS proxy
if test `ps ax | grep CORS | grep -v "grep" | wc -l` -gt 0; then
  echo "CORS proxy is running"
else
  echo "Starting CORS proxy"
  cd cors-cache-proxy
  node serverCORS &
  sleep 2
  cd ..
fi

