"""Project owner added

Revision ID: e16b4afaa164
Revises: af87eb95cafc
Create Date: 2020-10-25 08:12:06.724778

"""

# revision identifiers, used by Alembic.
revision = 'e16b4afaa164'
down_revision = 'af87eb95cafc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
