version: "3"
services:
  nginx:
    image: nginx:1.21.6
    container_name: portable_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vault:/vault
    networks:
      econet:
    ports:
      - 8088:80
    depends_on:
      - ecotaxafront
      - ecotaxaback
  ecotaxafront:
    image: ecotaxa/ecotaxa_front:latest
    container_name: portable_ecotaxafront
    volumes:
      - ./front_config:/app/config
    networks:
      econet:
    depends_on:
      - ecotaxaback
  ecotaxaback:
    image: ecotaxa/ecotaxa_back:latest
    container_name: portable_ecotaxaback
    volumes:
      - ./back_config.ini:/config.ini
      - ./ftp_area:/ftp_area
      - ./file_srv:/file_srv
      - ./vault:/vault
      - ./models:/models
      - temp_jobs:/temp_jobs
      - ./eco_users_files:/eco_users_files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      econet:
    depends_on:
      - pgdb
  ecotaxagpuback:
    image: ecotaxa/ecotaxa_gpu_back:latest
    container_name: portable_ecotaxagpuback
    restart: always
    volumes:
      - ./back_config.ini:/config.ini
      - ./vault:/vault
      - ./models:/models
      - temp_jobs:/temp_jobs
    networks:
      econet:
    depends_on:
      - pgdb
  pgdb:
    image: pgvector/pgvector:pg14
    container_name: portable_pgdb_1
    networks:
      econet:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
networks:
  econet:
    driver: bridge
volumes:
  temp_jobs: